package gormrepo

func AllModels() []any {
	return []any{
		&UserModel{},
		&RoleModel{},
		&BindingModel{},
		&PolicyRuleModel{},
		&SystemSettingModel{},
		&PluginModel{},
		&PluginRouteModel{},
		&PluginReleaseModel{},
		&PermissionResourceModel{},
		&MenuNodeModel{},
		&FileObjectModel{},
		&DictionaryTypeModel{},
		&DictionaryItemModel{},
		&DepartmentModel{},
		&PositionModel{},
		&UserAssignmentModel{},
		&AuditRecordModel{},
		&AuditEventModel{},
		&PharmaEmployeeModel{},
		&PharmaProductModel{},
		&PharmaSupplierModel{},
		&PharmaCustomerModel{},
		&PharmaWarehouseModel{},
		&PharmaStockBatchModel{},
		&PharmaStockBalanceModel{},
		&PharmaStockLedgerModel{},
		&PharmaStockLockModel{},
		&PharmaPurchaseRequestModel{},
		&PharmaPurchaseOrderModel{},
		&PharmaPurchaseInboundModel{},
		&PharmaSalesOrderModel{},
		&PharmaSalesOutboundModel{},
		&PharmaStocktakeModel{},
		&PharmaTransferModel{},
	}
}
