package gormrepo

func AllModels() []any {
	return []any{
		&UserModel{},
		&RoleModel{},
		&BindingModel{},
		&PolicyRuleModel{},
		&SystemSettingModel{},
		&PluginModel{},
		&PluginMigrationModel{},
		&PluginRouteModel{},
		&PluginReleaseModel{},
		&PluginDataMutationModel{},
		&PluginEventOutboxModel{},
		&PluginEventInboxModel{},
		&DocumentNumberSequenceModel{},
		&DocumentNumberIssueModel{},
		&DocumentWorkflowBindingModel{},
		&DocumentWorkflowActionModel{},
		&DocumentAttachmentModel{},
		&DocumentCommentModel{},
		&DocumentTimelineEventModel{},
		&PermissionResourceModel{},
		&MenuNodeModel{},
		&FileObjectModel{},
		&DictionaryTypeModel{},
		&DictionaryItemModel{},
		&DepartmentModel{},
		&PositionModel{},
		&UserAssignmentModel{},
		&AuditRecordModel{},
		&AuditEventModel{},
		&WorkflowDefinitionModel{},
		&WorkflowNodeModel{},
		&WorkflowNodeAssigneeModel{},
		&WorkflowTransitionModel{},
		&WorkflowInstanceModel{},
		&WorkflowTaskModel{},
		&WorkflowActionModel{},
		&WorkflowSubstitutionModel{},
		&WorkflowSignatureReceiptModel{},
		&NotificationItemModel{},
		&NotificationReminderRuleModel{},
		&NotificationDeliveryAttemptModel{},
		&JobModel{},
	}
}
