CREATE TABLE IF NOT EXISTS roles (
	id VARCHAR(64) PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	role_key VARCHAR(64) NOT NULL UNIQUE,
	description VARCHAR(255) NOT NULL DEFAULT '',
	builtin TINYINT(1) NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
	user_id VARCHAR(64) NOT NULL,
	role_id VARCHAR(64) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, role_id)
);

