CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(64) PRIMARY KEY,
	username VARCHAR(64) NOT NULL UNIQUE,
	display_name VARCHAR(128) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	status VARCHAR(16) NOT NULL DEFAULT 'active',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

