CREATE TABLE IF NOT EXISTS sk_file_objects (
	id VARCHAR(64) PRIMARY KEY,
	object_key VARCHAR(256) NOT NULL,
	name VARCHAR(255) NOT NULL,
	size_bytes BIGINT NOT NULL DEFAULT 0,
	mime VARCHAR(128) NOT NULL,
	hash VARCHAR(256) NOT NULL,
	owner_type VARCHAR(64) NOT NULL,
	owner_id VARCHAR(64) NOT NULL,
	visibility VARCHAR(32) NOT NULL DEFAULT 'private',
	storage_driver VARCHAR(64) NOT NULL,
	status VARCHAR(32) NOT NULL DEFAULT 'pending',
	source_module VARCHAR(64) NOT NULL,
	source_plugin_id VARCHAR(64) NOT NULL DEFAULT '',
	metadata_json LONGTEXT NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	UNIQUE KEY uk_file_objects_key (object_key),
	KEY idx_file_objects_owner (owner_type, owner_id),
	KEY idx_file_objects_visibility_status (visibility, status),
	KEY idx_file_objects_storage_status (storage_driver, status),
	KEY idx_file_objects_source (source_module, source_plugin_id),
	KEY idx_file_objects_status_updated (status, updated_at),
	KEY idx_file_objects_hash (hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
