CREATE TABLE IF NOT EXISTS sk_plugin_routes (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	plugin_id VARCHAR(128) NOT NULL,
	route_type VARCHAR(32) NOT NULL,
	route_path VARCHAR(512) NOT NULL,
	open_mode VARCHAR(32) NULL,
	permission_key VARCHAR(128) NULL,
	is_enabled TINYINT(1) NOT NULL DEFAULT 1,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	KEY idx_plugin_route (plugin_id, route_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sk_plugin_releases (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	plugin_id VARCHAR(128) NOT NULL,
	release_version VARCHAR(64) NOT NULL,
	package_name VARCHAR(256) NULL,
	package_hash VARCHAR(128) NULL,
	package_size BIGINT UNSIGNED NULL,
	signature TEXT NULL,
	changelog TEXT NULL,
	uploaded_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	KEY idx_plugin_release (plugin_id, release_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
