CREATE TABLE IF NOT EXISTS sk_audit_events (
	id VARCHAR(64) PRIMARY KEY,
	event_type VARCHAR(32) NOT NULL,
	action VARCHAR(192) NOT NULL,
	actor_type VARCHAR(64) NOT NULL,
	actor_id VARCHAR(64) NOT NULL DEFAULT '',
	actor_name VARCHAR(128) NOT NULL DEFAULT '',
	resource_type VARCHAR(64) NOT NULL,
	resource_id VARCHAR(128) NOT NULL DEFAULT '',
	resource_name VARCHAR(128) NOT NULL DEFAULT '',
	result VARCHAR(32) NOT NULL,
	risk VARCHAR(32) NOT NULL DEFAULT 'low',
	trace_id VARCHAR(128) NOT NULL DEFAULT '',
	request_id VARCHAR(128) NOT NULL DEFAULT '',
	request_method VARCHAR(16) NOT NULL DEFAULT '',
	request_path VARCHAR(512) NOT NULL DEFAULT '',
	request_ip VARCHAR(64) NOT NULL DEFAULT '',
	user_agent VARCHAR(512) NOT NULL DEFAULT '',
	metadata_json LONGTEXT NULL,
	source_json LONGTEXT NULL,
	occurred_at DATETIME(3) NOT NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	KEY idx_audit_events_type_time (event_type, occurred_at),
	KEY idx_audit_events_actor_time (actor_id, occurred_at),
	KEY idx_audit_events_action_time (action, occurred_at),
	KEY idx_audit_events_resource_time (resource_type, resource_id, occurred_at),
	KEY idx_audit_events_result_time (result, occurred_at),
	KEY idx_audit_events_risk_time (risk, occurred_at),
	KEY idx_audit_events_trace (trace_id),
	KEY idx_audit_events_request (request_id),
	KEY idx_audit_events_occurred (occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
