CREATE TABLE IF NOT EXISTS sk_plugin_event_outbox (
    id VARCHAR(128) NOT NULL,
    publisher VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    event_name VARCHAR(128) NOT NULL,
    schema_version BIGINT UNSIGNED NOT NULL,
    payload_type VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    organization_id VARCHAR(128) NOT NULL DEFAULT '',
    owner_id VARCHAR(128) NOT NULL DEFAULT '',
    correlation_id VARCHAR(128) NOT NULL,
    causation_id VARCHAR(128) NOT NULL DEFAULT '',
    subject_type VARCHAR(128) NOT NULL DEFAULT '',
    subject_id VARCHAR(128) NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 5,
    next_attempt_at DATETIME(6) NOT NULL,
    lease_owner VARCHAR(128) NOT NULL DEFAULT '',
    lease_token VARCHAR(64) NOT NULL DEFAULT '',
    lease_expires_at DATETIME(6) NULL,
    last_error TEXT NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    delivered_at DATETIME(6) NULL,
    dead_lettered_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_plugin_event_idempotency (publisher, idempotency_key),
    KEY idx_plugin_event_dispatch (status, next_attempt_at, publisher),
    KEY idx_plugin_event_lease_expiry (lease_expires_at),
    KEY idx_plugin_event_correlation (correlation_id)
);
