CREATE TABLE IF NOT EXISTS sk_plugin_event_outbox (
    id VARCHAR(128) NOT NULL,
    publisher VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    event_name VARCHAR(128) NOT NULL,
    schema_version BIGINT UNSIGNED NOT NULL,
    payload_type VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    organization_id VARCHAR(128) NOT NULL DEFAULT '',
    owner_id VARCHAR(128) NOT NULL DEFAULT '',
    correlation_id VARCHAR(128) NOT NULL,
    causation_id VARCHAR(128) NOT NULL DEFAULT '',
    subject_type VARCHAR(128) NOT NULL DEFAULT '',
    subject_id VARCHAR(128) NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_plugin_event_idempotency (publisher, idempotency_key),
    KEY idx_plugin_event_pending (status, publisher, tenant_id, created_at),
    KEY idx_plugin_event_correlation (correlation_id)
);
