CREATE TABLE IF NOT EXISTS sk_plugin_event_inbox (
    delivery_id VARCHAR(128) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    subscriber VARCHAR(64) NOT NULL,
    handler VARCHAR(128) NOT NULL,
    publisher VARCHAR(64) NOT NULL,
    event_name VARCHAR(128) NOT NULL,
    schema_version BIGINT UNSIGNED NOT NULL,
    tenant_id VARCHAR(128) NOT NULL DEFAULT '',
    delivery_json TEXT NOT NULL,
    status VARCHAR(24) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    lease_owner VARCHAR(128) NOT NULL DEFAULT '',
    lease_token VARCHAR(64) NOT NULL DEFAULT '',
    lease_expires_at DATETIME(6) NULL,
    last_error TEXT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    processed_at DATETIME(6) NULL,
    PRIMARY KEY (delivery_id),
    KEY idx_plugin_event_inbox_event (event_id),
    KEY idx_plugin_event_inbox_status (status, subscriber),
    KEY idx_plugin_event_inbox_lease (lease_expires_at)
);
