CREATE TABLE IF NOT EXISTS sk_jobs (
	id VARCHAR(128) PRIMARY KEY,
	namespace VARCHAR(128) NOT NULL,
	kind VARCHAR(128) NOT NULL,
	idempotency_key VARCHAR(191) NULL,
	payload_json LONGTEXT NOT NULL,
	status VARCHAR(32) NOT NULL,
	run_at DATETIME(3) NOT NULL,
	max_attempts INT NOT NULL,
	attempt_count INT NOT NULL,
	lease_owner VARCHAR(128) NOT NULL,
	lease_token VARCHAR(64) NOT NULL,
	lease_expires_at DATETIME(3) NULL,
	last_error TEXT NOT NULL,
	result_json LONGTEXT NOT NULL,
	created_at DATETIME(3) NOT NULL,
	updated_at DATETIME(3) NOT NULL,
	completed_at DATETIME(3) NULL,
	dead_lettered_at DATETIME(3) NULL,
	UNIQUE KEY idx_job_idempotency (namespace, idempotency_key),
	KEY idx_job_namespace_status (namespace, status),
	KEY idx_job_kind_status (kind, status),
	KEY idx_job_due (status, run_at),
	KEY idx_job_lease_expiry (lease_expires_at),
	KEY idx_job_dead_lettered (dead_lettered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
