apiVersion: v1
kind: Service
metadata:
  name: skoll
  labels:
    app.kubernetes.io/name: skoll
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: skoll
  ports:
    - name: http
      port: 80
      targetPort: http
