CREATE TABLE IF NOT EXISTS sk_plugin_migrations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	plugin_id VARCHAR(128) NOT NULL,
	version BIGINT NOT NULL,
	name VARCHAR(255) NOT NULL,
	checksum VARCHAR(64) NOT NULL,
	applied_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT idx_plugin_migration_version UNIQUE (plugin_id, version)
);

CREATE INDEX IF NOT EXISTS idx_sk_plugin_migrations_applied_at ON sk_plugin_migrations (applied_at);
