CREATE TABLE IF NOT EXISTS sk_plugin_routes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	plugin_id VARCHAR(128) NOT NULL,
	route_type VARCHAR(32) NOT NULL,
	route_path VARCHAR(512) NOT NULL,
	open_mode VARCHAR(32) NULL,
	permission_key VARCHAR(128) NULL,
	is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sk_plugin_route ON sk_plugin_routes (plugin_id, route_type);

CREATE TABLE IF NOT EXISTS sk_plugin_releases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	plugin_id VARCHAR(128) NOT NULL,
	release_version VARCHAR(64) NOT NULL,
	package_name VARCHAR(256) NULL,
	package_hash VARCHAR(128) NULL,
	package_size BIGINT NULL,
	signature TEXT NULL,
	changelog TEXT NULL,
	uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sk_plugin_release ON sk_plugin_releases (plugin_id, release_version);
