CREATE TABLE IF NOT EXISTS sk_plugins (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	plugin_id VARCHAR(128) NOT NULL,
	name VARCHAR(128) NOT NULL,
	version VARCHAR(64) NOT NULL,
	description VARCHAR(512) NULL,
	state VARCHAR(32) NOT NULL,
	source VARCHAR(512) NULL,
	ui_mode VARCHAR(64) NULL,
	frontend_entry VARCHAR(512) NULL,
	system_builtin BOOLEAN NOT NULL DEFAULT FALSE,
	permissions_json TEXT NULL,
	dependencies_json TEXT NULL,
	installed_at TIMESTAMPTZ NULL,
	enabled_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT uk_plugin_id UNIQUE (plugin_id)
);

CREATE INDEX IF NOT EXISTS idx_sk_plugins_state ON sk_plugins (state);
