package main

import "time"

type MetricCard struct {
	Label  string `json:"label"`
	Value  string `json:"value"`
	Change string `json:"change"`
	Tone   string `json:"tone"`
}

type FocusArea struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
	Region  string `json:"region"`
	Stage   string `json:"stage"`
}

// Overview summarizes runtime signals for the separated demo plugin.
//
// Usage example:
//
//	svc := NewDemoService()
//	overview := svc.BuildOverview("demo", time.Now().UTC())
//	// overview.Highlights can be rendered directly in a dashboard card.
type Overview struct {
	Company     string       `json:"company"`
	Headline    string       `json:"headline"`
	PluginID    string       `json:"pluginId"`
	GeneratedAt time.Time    `json:"generatedAt"`
	Status      string       `json:"status"`
	Highlights  []string     `json:"highlights"`
	Stats       []MetricCard `json:"stats"`
	FocusAreas  []FocusArea  `json:"focusAreas"`
}

// DashboardContext captures the key runtime inputs for recommendation scoring.
//
// Fields:
// - ActiveUsers: current online users in admin console.
// - ErrorCount: number of plugin related errors in the recent window.
// - RequestsPerMinute: rolling average request throughput.
type DashboardContext struct {
	ActiveUsers       int     `json:"activeUsers"`
	ErrorCount        int     `json:"errorCount"`
	RequestsPerMinute float64 `json:"requestsPerMinute"`
}

// Recommendation describes one actionable suggestion generated by the plugin.
type Recommendation struct {
	Title    string `json:"title"`
	Reason   string `json:"reason"`
	Priority string `json:"priority"`
	Owner    string `json:"owner"`
	Window   string `json:"window"`
}

// DemoService provides runtime summary and recommendation capabilities.
type DemoService struct{}

// NewDemoService creates a service instance for separated demo use cases.
func NewDemoService() *DemoService {
	return &DemoService{}
}

// Name returns a human readable service identifier.
func (s *DemoService) Name() string {
	return "demo-separated-service"
}

// BuildOverview builds an operational summary for a plugin instance.
//
// Parameters:
// - pluginID: target plugin identifier.
// - now: snapshot timestamp.
func (s *DemoService) BuildOverview(pluginID string, now time.Time) Overview {
	status := "healthy"
	highlights := []string{
		"frontend bundle connected with backend metadata",
		"plugin routes are available for runtime probing",
		"plugin permissions declared and validated",
	}
	stats := []MetricCard{
		{Label: "Pipeline Value", Value: "$12.4M", Change: "+18% quarter-on-quarter", Tone: "accent"},
		{Label: "Live Regions", Value: "06", Change: "APAC launch unlocked", Tone: "calm"},
		{Label: "Studio Utilization", Value: "92%", Change: "Two new lab sprints added", Tone: "warm"},
	}
	focusAreas := []FocusArea{
		{Title: "Retail Atelier", Summary: "Convert flagship stores into low-friction pickup lounges with guided discovery walls.", Region: "Shanghai", Stage: "prototype"},
		{Title: "Field Service Kit", Summary: "Bundle diagnostics, repair scripts, and concierge messaging into one tablet workflow.", Region: "Shenzhen", Stage: "pilot"},
		{Title: "Executive Briefing Deck", Summary: "Turn weekly platform signals into a board-ready narrative with market and risk framing.", Region: "Global", Stage: "active"},
	}
	if pluginID == "" {
		pluginID = "unknown"
		status = "degraded"
		highlights = append(highlights, "plugin id missing in request context")
	}

	return Overview{
		Company:     "Aurora Forge",
		Headline:    "A sample child-application homepage that feels like a real company studio, not a plugin placeholder.",
		PluginID:    pluginID,
		GeneratedAt: now,
		Status:      status,
		Highlights:  highlights,
		Stats:       stats,
		FocusAreas:  focusAreas,
	}
}

// RecommendActions generates prioritized suggestions based on dashboard context.
//
// Usage example:
//
//	recs := svc.RecommendActions(DashboardContext{ActiveUsers: 120, ErrorCount: 4, RequestsPerMinute: 220})
func (s *DemoService) RecommendActions(ctx DashboardContext) []Recommendation {
	recs := make([]Recommendation, 0, 3)

	if ctx.ErrorCount > 0 {
		recs = append(recs, Recommendation{
			Title:    "Review plugin error traces",
			Reason:   "error_count is greater than zero",
			Priority: "high",
			Owner:    "Platform Reliability",
			Window:   "today",
		})
	}

	if ctx.RequestsPerMinute > 180 {
		recs = append(recs, Recommendation{
			Title:    "Enable cache for plugin dashboard endpoints",
			Reason:   "high request throughput detected",
			Priority: "medium",
			Owner:    "Edge Delivery",
			Window:   "this sprint",
		})
	}

	if ctx.ActiveUsers < 20 {
		recs = append(recs, Recommendation{
			Title:    "Promote plugin entry in navigation",
			Reason:   "active user count is below expected demo traffic",
			Priority: "low",
			Owner:    "Growth Design",
			Window:   "next week",
		})
	}

	if len(recs) == 0 {
		recs = append(recs, Recommendation{
			Title:    "Keep current plugin rollout policy",
			Reason:   "runtime metrics are within expected threshold",
			Priority: "low",
			Owner:    "Program Office",
			Window:   "monitor",
		})
	}

	return recs
}
