package main

import "time"

// Overview summarizes runtime signals for the separated demo plugin.
//
// Usage example:
//
//	svc := NewDemoService()
//	overview := svc.BuildOverview("demo", time.Now().UTC())
//	// overview.Highlights can be rendered directly in a dashboard card.
type Overview struct {
	PluginID    string    `json:"pluginId"`
	GeneratedAt time.Time `json:"generatedAt"`
	Status      string    `json:"status"`
	Highlights  []string  `json:"highlights"`
}

// DashboardContext captures the key runtime inputs for recommendation scoring.
//
// Fields:
// - ActiveUsers: current online users in admin console.
// - ErrorCount: number of plugin related errors in the recent window.
// - RequestsPerMinute: rolling average request throughput.
type DashboardContext struct {
	ActiveUsers       int     `json:"activeUsers"`
	ErrorCount        int     `json:"errorCount"`
	RequestsPerMinute float64 `json:"requestsPerMinute"`
}

// Recommendation describes one actionable suggestion generated by the plugin.
type Recommendation struct {
	Title    string `json:"title"`
	Reason   string `json:"reason"`
	Priority string `json:"priority"`
}

// DemoService provides runtime summary and recommendation capabilities.
type DemoService struct{}

// NewDemoService creates a service instance for separated demo use cases.
func NewDemoService() *DemoService {
	return &DemoService{}
}

// Name returns a human readable service identifier.
func (s *DemoService) Name() string {
	return "demo-separated-service"
}

// BuildOverview builds an operational summary for a plugin instance.
//
// Parameters:
// - pluginID: target plugin identifier.
// - now: snapshot timestamp.
func (s *DemoService) BuildOverview(pluginID string, now time.Time) Overview {
	status := "healthy"
	highlights := []string{
		"frontend bundle connected with backend metadata",
		"plugin routes are available for runtime probing",
		"plugin permissions declared and validated",
	}
	if pluginID == "" {
		pluginID = "unknown"
		status = "degraded"
		highlights = append(highlights, "plugin id missing in request context")
	}

	return Overview{
		PluginID:    pluginID,
		GeneratedAt: now,
		Status:      status,
		Highlights:  highlights,
	}
}

// RecommendActions generates prioritized suggestions based on dashboard context.
//
// Usage example:
//
//	recs := svc.RecommendActions(DashboardContext{ActiveUsers: 120, ErrorCount: 4, RequestsPerMinute: 220})
func (s *DemoService) RecommendActions(ctx DashboardContext) []Recommendation {
	recs := make([]Recommendation, 0, 3)

	if ctx.ErrorCount > 0 {
		recs = append(recs, Recommendation{
			Title:    "Review plugin error traces",
			Reason:   "error_count is greater than zero",
			Priority: "high",
		})
	}

	if ctx.RequestsPerMinute > 180 {
		recs = append(recs, Recommendation{
			Title:    "Enable cache for plugin dashboard endpoints",
			Reason:   "high request throughput detected",
			Priority: "medium",
		})
	}

	if ctx.ActiveUsers < 20 {
		recs = append(recs, Recommendation{
			Title:    "Promote plugin entry in navigation",
			Reason:   "active user count is below expected demo traffic",
			Priority: "low",
		})
	}

	if len(recs) == 0 {
		recs = append(recs, Recommendation{
			Title:    "Keep current plugin rollout policy",
			Reason:   "runtime metrics are within expected threshold",
			Priority: "low",
		})
	}

	return recs
}
